### ISSUE TITLE
Need some clarification

### ISSUE THREAD

**Issue by giahuy98** [coinkite/coinkite-tap-proto#21]
I have some questions about protocol implementation, please help clarify

1. https://github.com/coinkite/coinkite-tap-proto/blob/master/cktap/proto.py#L264

``` python
        if resp.get('sealed', None) != True: # shouldn't it be resp.get('used', None)?
            raise RuntimeError(f"Slot {target} has not been used yet.")
 
```

2. https://github.com/coinkite/coinkite-tap-proto/blob/master/cktap/proto.py#L70

``` python
        if st.get('tampered'): # do we get 'tampered' here or when call 'dump' command? is 'tampered' flag exists for both Tapsigner and Satscard?
            print("WARNING: Card has set tampered flag!")
```

**Comment by scgbckbone** [comment]
1. it does the same thing. If slot is `unused`, `sealed` key will not be present in the response dict and therefore `resp.get('sealed', None) != True` --> `None != True` and we will raise unused error. But you're right explicit is better than implicit https://github.com/coinkite/coinkite-tap-proto/pull/22  --> thank you!
2. you'll get that print message for each command as `print("WARNING: Card has set tampered flag!")` is part of card initialization. To find out if card is tampered and not using CLI you should use `status` command and look for `tampered` key in response dict. It seems to me that you can get tampered flag on both SATSCARD and TAPSIGNER (but I only managed to brick SATSCARD [yet]) maybe @doc-hex can tell us more?
